/**
 * Library Service API
 * Library Service API Description
 *
 * OpenAPI spec version: 1.0
 * Contact: alonso.magarzo-external@es.dachser.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BookDTO { 
    copys?: number;
    title?: string;
}
